version: "3.8"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=supersecretkey
      - RATE_LIMIT=500    # tune per worker
      - RATE_BURST=1000
      - RATE_REFILL_SEC=60
      - CACHE_TTL=30
      - WORKERS=4
    depends_on:
      - redis
    ports:
      - "8000:8000"
